name: 'Build and Publish'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract-meta-information:
    uses: ./.github/workflows/extract-meta-information.yml
    with:
      path: "./"

  # Build for all platforms in parallel
  build-android:
    needs: extract-meta-information
    uses: ./.github/workflows/build-sign-android.yml
    with:
      name: "tauri-template"
      version: ${{ needs.extract-meta-information.outputs.version }}
      path: "./"
    secrets: inherit

  build-ios:
    needs: extract-meta-information
    uses: ./.github/workflows/build-sign-ios.yml
    with:
      name: "tauri-template"
      version: ${{ needs.extract-meta-information.outputs.version }}
      path: "./"
    secrets: inherit

  build-macos:
    needs: extract-meta-information
    uses: ./.github/workflows/build-sign-macos.yml
    with:
      name: "tauri-template"
      version: ${{ needs.extract-meta-information.outputs.version }}
      path: "./"
    secrets: inherit

  build-ubuntu:
    needs: extract-meta-information
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      name: "tauri-template"
      version: ${{ needs.extract-meta-information.outputs.version }}
      path: "./"
    secrets: inherit

  build-windows:
    needs: extract-meta-information
    uses: ./.github/workflows/build-windows.yml
    with:
      name: "tauri-template"
      version: ${{ needs.extract-meta-information.outputs.version }}
      path: "./"
    secrets: inherit

  # Summary job that depends on all builds
  build-summary:
    needs: [build-android, build-ios, build-macos, build-ubuntu, build-windows]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Android | ${{ needs.build-android.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| iOS | ${{ needs.build-ios.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| macOS | ${{ needs.build-macos.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Ubuntu | ${{ needs.build-ubuntu.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Windows | ${{ needs.build-windows.result }} |" >> $GITHUB_STEP_SUMMARY
      